import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/providers/authProvider";
import Header from "@/components/header";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
     <AuthProvider>

      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    <Header />
         {children}
  <Footer/>     
      </body>
              </AuthProvider>
    </html>
  );
}
