import { Download } from 'lucide-react'
import React from 'react'

const DowloadSummaryButton = ({title,summaryText,createdAt}:{
    title: string;
  createdAt: string;
  summaryText: string;
}) => {

    const handleDowload= ()=>{
        const summaryContent= ` # ${title}
        Generated Summary
        Generated on: ${new Date(createdAt).toLocaleDateString()}
        
        ${summaryText}
        
        Generated by pdfSummary`;

        const blob = new Blob([summaryContent],{type: 'text/plain'});
        const url= URL.createObjectURL(blob)

        const link = document.createElement('a')
        link.href= url
        link.download = `summary-${title.replace(/[^a-z0-9]/gi,'-')}.txt`
        link.click()

        document.body.removeChild(link);
        URL.revokeObjectURL(url)
    }


  return (
   <button onClick={handleDowload} className="bg-gray-100 text-gray-700 py-2 px-4 rounded-lg font-medium hover:bg-gray-200 transition-colors duration-200 flex items-center justify-center">
                        <Download className="w-4 h-4" />
                      </button>
  )
}

export default DowloadSummaryButton